name: seamless-jobserver
channels:
  - conda-forge
dependencies:
  - aiohttp
  - pip
  - pip:
      - -e .
      - -e ./seamless-base
      - -e ./seamless-transformer
      - -e ./seamless-config
      - -e ./seamless-remote
